{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.name }}
  labels:
    {{- include "al-deployment.labels" . | nindent 4 }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.name }}
  dataFrom:
  - extract:
      key: {{ .Values.externalSecrets.key }}
{{- end }}
