apiVersion: v1
kind: Service
metadata:
  name: {{ include "al-deployment.fullname" . }}
  labels:
    {{- include "al-deployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "al-deployment.selectorLabels" . | nindent 4 }}